### ISSUE TITLE
debug单个we文件报network error

### ISSUE THREAD

**Issue by squirrelx** [weexteam/weex_devtools_android#11]
采用weex debug ***.we   能够打开chrome并生成左右两个二维码，扫描左边的能够进入playground的调试，扫描我的we文件生成的二维码 报network error

**Comment by littleseven** [comment]
@squirrelx 你的操作系统，和 weextoolkit版本麻烦告知一下

**Comment by squirrelx** [comment]
@littleseven win 7 sp1  32位

**Comment by squirrelx** [comment]
@littleseven 有结论吗

**Comment by littleseven** [comment]
fixed, 更新最新版本weextoolkit即可
