### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by 750813987** [weexteam/weex_devtools_android#2]
![image](https://cloud.githubusercontent.com/assets/19163532/17173485/b8904670-542d-11e6-94c7-b0c53d38b6af.png)

少了单引号，应该是类似这样的
![image](https://cloud.githubusercontent.com/assets/19163532/17173524/eb69247c-542d-11e6-93f6-e0653b02b37b.png)

**Comment by littleseven** [comment]
updated! thanks
