### ISSUE TITLE
在CSS Style中添加WXDomObject的ref和type

### ISSUE THREAD

**Issue by misakuo** [weexteam/weex_devtools_android#26]
最近在调试weex的native渲染逻辑，因为实际渲染出的布局层级和we文件template中定义的层级并不是一一对应的，所以在native视图里找起来就比较困难，我这边hack了一下，在`WXComponent`里获取到了WXDomObject的ref和type属性，并通过`setTag`方法附加到dom对应的View上，在devtools的`CSS#getMatchedStylesForNode`方法中通过`getTag`取出来，并展示到CSS属性内，效果大概是这样：    
![QQ20160927-0@2x.png](https://ooo.0o0.ooo/2016/09/27/57ea125bdde9a.png)    
不知道devtool能不能官方支持一下？

**Comment by littleseven** [comment]
##### Element
这里展示的是在Android／iOS上的native DOM树，及其style属性，和layout图。鼠标在DOM 树移动时，在device（或模拟器）上对应节点会高亮显示，有助于native开发者定位和发现节点，且具有在图像上搜索节点的能力。
##### native view element
![native-element](https://img.alicdn.com/tps/TB16L3ENXXXXXcsXVXXXXXXXXXX-2878-1798.png "native-element")

##### weex dom element
![dom-element](https://img.alicdn.com/tps/TB1TsMuNXXXXXcsaXXXXXXXXXXX-2450-1460.png "dom-element")

**Comment by misakuo** [comment]
thanks!
