### ISSUE TITLE
playground扫描后applist没有反应

### ISSUE THREAD

**Issue by squirrelx** [weexteam/weex_devtools_android#27]
扫描后 applist没有反应，android手机上的playground应用产生了debug模式，但是web界面上没有inspector和debug的按钮，  week-tookit debug -v的结果是    0.2.48

**Comment by littleseven** [comment]
检查一下网络状况，1.是否联网 2.是否连接了代理（不支持）

**Comment by squirrelx** [comment]
@littleseven   我weex debug  *.we   用playground扫描后是可以连上并看到我写的页面的，但是applist什么都没有，在web上也看不到inspector和debug按钮

**Comment by littleseven** [comment]
weex debug *.we 会产生两个二维码，最左侧的二维码即为与debug server建立连接的二维码，第二个二维码为we生成的bundle对应的二维码。直接扫第二个二维码会下载并载入bundle，**只有扫描第一个二维码才会发起连接debug server的请求**。

解决步骤：
* 1. 扫描第一个二维码连接debug server，若成功则会看到applist
* 2. 扫描第二个二维码，则载入*.we对应生成的bundle

**Comment by squirrelx** [comment]
@littleseven 链接第一个也不行，applist不会有反应。  下了最新的playground后就好了。。。
